# xwealth information
xwealth:
  datx:
    url:
      root: https://dev-xwealth.datxasia.com/
    api:
      login: https://api.datx.vn/api/auth/login
      root: https://core.datx.vn/graphql
    account:
      email: huong.nguyen@datx.com.vn
      password: Pickgunny123@


